In [ ]:
#1 incremental learning as there is always going to be new and different customers so it would keep itself updated
#2, supervised learning because it has to learn and then filter out the spam instead of letting it pick what it wants to filter out itself
#3 it's usually done after the prediction to make sure that the data that you want to extract seems accurate and consice
#4  e, i want to say for sure C but a would help i feel like

In [25]:
import boto3 
import pandas as pd
import numpy as np

## defining the bucket
s3 = boto3.resource('s3')
bucket_name = 'rickydata445'
bucket = s3.Bucket(bucket_name)

## defining the csv file
file_key = 'Real_Estate.csv'

bucket_object = bucket.Object(file_key)
file_object = bucket_object.get()
file_content_stream = file_object.get('Body')

## reading the csv file
house_price = pd.read_csv(file_content_stream)
house_price.head()

No  transaction_date  house_age  distance_to_the_nearest_MRT_station  \
0   1          2012.917       32.0                             84.87882   
1   2          2012.917       19.5                            306.59470   
2   3          2013.583       13.3                            561.98450   
3   4          2013.500       13.3                            561.98450   
4   5          2012.833        5.0                            390.56840   

   number_of_convenience_stores  latitude  longitude  house_price_of_unit_area  
0                            10  24.98298  121.54024                      37.9  
1                             9  24.98034  121.53951                      42.2  
2                             5  24.98746  121.54391                      47.3  
3                             5  24.98746  121.54391                      54.8  
4                             5  24.97937  121.54245                      43.1

In [3]:
## dropping the no column
house_price = house_price.drop(columns = ['No', 'transaction_date'])
house_price.head()

house_age  distance_to_the_nearest_MRT_station  \
0       32.0                             84.87882   
1       19.5                            306.59470   
2       13.3                            561.98450   
3       13.3                            561.98450   
4        5.0                            390.56840   

   number_of_convenience_stores  latitude  longitude  house_price_of_unit_area  
0                            10  24.98298  121.54024                      37.9  
1                             9  24.98034  121.53951                      42.2  
2                             5  24.98746  121.54391                      47.3  
3                             5  24.98746  121.54391                      54.8  
4                             5  24.97937  121.54245                      43.1

In [4]:
from sklearn.model_selection import train_test_split

## defining the input and target variables
X = house_price.drop(columns = ['house_price_of_unit_area'], axis = 1)
Y = house_price['house_price_of_unit_area']

## splitting the data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

## building the linear model
from sklearn.linear_model import LinearRegression

lm_md = LinearRegression().fit(X_train, Y_train)
lm_md.coef_

array([-2.71080885e-01, -3.90668907e-03,  1.42503173e+00,  2.18384344e+02,
        3.91569394e+00])

In [5]:
## predicting on test
preds = lm_md.predict(X_test)
preds

array([47.24976864, 25.91724961, 45.2435774 , 32.18753297, 29.56791092,
       41.88505502, 39.95386885, 35.93212483, 38.50168385, 45.9911728 ,
       37.01443399, 32.45575644, 46.40176774, 33.12825222, 35.11313722,
       14.420648  , 29.73725941, 23.96169294, 44.30775301, 53.80015712,
       48.70575508, 53.21510473, 39.92125875, 41.77662267, 23.2460617 ,
       50.37887351, 29.73334931, 33.88503372, 45.96388413, 27.89577944,
       30.80476823, 33.92202556, 43.05035163, 37.74036694, 41.48046383,
       32.476566  , 14.97894672, 41.16661332, 14.81629819, 50.31395004,
       45.07844657, 38.2729703 , 29.55941617, 40.29928206, 32.50997262,
       35.90681071, 27.21343974, 14.74568122, 40.24506588, 35.23293506,
       38.80283828, 49.45984029, 29.64842778, 50.37887351, 39.80843135,
       14.68367357, 47.40931709, 34.49503784, 37.17887306, 38.03680922,
       44.51918272, 31.97318916, 42.51688356, 43.3408366 , 35.57587778,
       46.06739425, 32.53636049, 39.33370463, 47.89296413, 49.43

In [6]:
## computing the mse
mse = np.mean(np.power(preds - Y_test, 2))
mse

157.33244583952307

In [7]:
## defining the input and target variables
A = house_price[['house_age', 'number_of_convenience_stores', 'latitude', 'longitude']]
B = house_price['house_price_of_unit_area']

In [10]:
## splitting the data
A_train, A_test, B_train, B_test = train_test_split(A, B, test_size = 0.2)

## building the linear model
from sklearn.linear_model import LinearRegression

lm_md = LinearRegression().fit(A_train, B_train)
lm_md.coef_

array([-2.59200573e-01,  1.61735414e+00,  3.58617710e+02,  1.85555556e+02])

In [11]:
## predicting on test
preds = lm_md.predict(A_test)
preds

array([54.64284075, 34.00242917, 38.73378589, 16.86615022, 46.05328641,
       40.07510398, 17.24587076, 52.81794869, 32.27175182, 37.75898988,
       49.34167834, 31.88895951, 31.26388187, 40.179567  , 15.48450436,
       33.97650911, 48.04506449, 35.79778805, 34.95680768, 47.4183349 ,
       15.79096071, 43.17335846, 27.8932555 , 16.90513952, 48.58999084,
       33.70823747, 20.38615307, 36.09564612, 44.88531408, 43.27821333,
       46.5256919 , 46.58839388, 39.55421258, 33.94759426, 44.75302566,
       14.0781479 , 46.80373354, 44.24339285, 20.39814249, 31.60010031,
       30.81966088, 20.35414268, 46.66615405, 49.51094109, 46.66615405,
       26.76944926, 35.21002335, 52.94754898, 47.1845552 , 42.21983054,
       34.88139453, 33.52896057, 30.42422919, 31.69215347, 42.70916268,
       42.63140251, 20.45943886, 50.08946309, 46.58839388, 44.26936463,
       44.30450559, 35.42292458, 26.76293246, 34.02834922, 42.32351077,
       17.11249998, 36.22090558, 29.81871971, 42.57956239, 50.96

In [12]:
## computing the mse
mse = np.mean(np.power(preds - B_test, 2))
mse

57.91525860289607

In [ ]:
# by comparing both models you can see that the mse is very low on the second one, making it the one we would want to use

In [17]:
'''from sklearn.model_selection import LeaveOneOut

## defining the list to store results
md1_results = list()

cv = LeaveOneOut()

for train_ix, test_ix in cv.split(X):
    #splitting the data
    X_train, X_test = X.loc[train_ix], X.loc[test_ix]
    Y_train, Y_test = Y.loc[train_ix], Y.loc[test_ix]
    
    ## building the linear regression model
    lm_md = LinearRegression().fit(X_train, Y_train)
    
    ##predicitng on the test set
    pred = lm_md.predict(X_test)
    
    ## storing results
    md1_results.append(pred[0])

## computing the mse
mse_md1 = np.mean(np.power(md1_results - Y, 2))
mse_md1'''

81.68169281258623

In [24]:
## Defining list to store results
md1_results = []
md2_results = []
for i in range(0, 100):
## Splitting the data
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
    ## Defining data for the second model
    X_train_new = X_train.drop(columns = [’distance_to_the_nearest_MRT_station’],
    axis = 1)
    X_test_new = X_test.drop(columns = [’distance_to_the_nearest_MRT_station’],
    axis = 1)
    ## Model 1
    md1 = LinearRegression().fit(X_train, Y_train)
    pred1 = md1.predict(X_test)
    mse1 = np.mean(np.power(pred1 - Y_test, 2))
    md1_results.append(mse1)
    ## Model 2
    md2 = LinearRegression().fit(X_train_new, Y_train)
    pred2 = md2.predict(X_test_new)
    mse2 = np.mean(np.power(pred2 - Y_test, 2))
    md2_results.append(mse2)
4
## Plotting iteration results
fig = plt.figure(figsize = (12, 8))
iterations = range(0, 100)
plt.plot(iterations, md1_results, marker = ’o’, color = ’blue’,
label = ’Model (d)’)
plt.plot(iterations, md2_results, marker = ’o’, color = ’orange’,
label = ’Model (e)’)
plt.xlabel(’Number of Iteration’)
plt.ylabel(’MSE’)
plt.legend()
plt.grid()
plt.show()

88.19377339447

In [ ]:
## according to the loops the first testing model has performed better due it it's low MSE, making it the one you would want to choose